### ISSUE TITLE
Unhandled exception when opening Script > Execute window

### ISSUE THREAD

**Issue by ascended121** [nasa/CCDD#24]
When attempting to open Script > Execute I get the following exception printed to the command line and the Execute Scripts window appears but only contains the text `Select script association(s) to execute` with none of the normal selection boxes or buttons.

Script > Manage window opens correctly and scripts can be executed from there, so not urgent. 

Please let me know if there's additional information I can provide. This was observed on version 1.2.50.

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at javax.swing.text.DefaultStyledDocument.getParagraphElement(Unknown Source)
        at javax.swing.text.StyledEditorKit$AttributeTracker.updateInputAttributes(Unknown Source)
        at javax.swing.text.StyledEditorKit$AttributeTracker.caretUpdate(Unknown Source)
        at javax.swing.text.JTextComponent.fireCaretUpdate(Unknown Source)
        at javax.swing.text.JTextComponent$MutableCaretEvent.fire(Unknown Source)
        at javax.swing.text.JTextComponent$MutableCaretEvent.stateChanged(Unknown Source)
        at javax.swing.text.DefaultCaret.fireStateChanged(Unknown Source)
        at javax.swing.text.DefaultCaret.changeCaretPosition(Unknown Source)
        at javax.swing.text.DefaultCaret.handleSetDot(Unknown Source)
        at javax.swing.text.DefaultCaret.setDot(Unknown Source)
        at javax.swing.text.DefaultCaret$Handler.removeUpdate(Unknown Source)
        at javax.swing.text.AbstractDocument.fireRemoveUpdate(Unknown Source)
        at javax.swing.text.AbstractDocument.handleRemove(Unknown Source)
        at javax.swing.text.AbstractDocument.remove(Unknown Source)
        at javax.swing.JEditorPane.setText(Unknown Source)
        at CCDD.CcddJTableHandler$HTMLCellRenderer.getTableCellRendererComponent(CcddJTableHandler.java:1927)
        at javax.swing.JTable.prepareRenderer(Unknown Source)
        at CCDD.CcddJTableHandler.updateRowHeights(CcddJTableHandler.java:3976)
        at CCDD.CcddJTableHandler.tableChanged(CcddJTableHandler.java:3948)
        at CCDD.CcddJTableHandler$11.run(CcddJTableHandler.java:4086)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at javax.swing.text.DefaultStyledDocument$ElementBuffer.create(Unknown Source)
        at javax.swing.text.DefaultStyledDocument.create(Unknown Source)
        at javax.swing.text.html.HTMLDocument.create(Unknown Source)
        at javax.swing.text.html.HTMLDocument$HTMLReader.flushBuffer(Unknown Source)
        at javax.swing.text.html.HTMLDocument$HTMLReader.flush(Unknown Source)
        at javax.swing.text.html.HTMLEditorKit.read(Unknown Source)
        at javax.swing.JEditorPane.setText(Unknown Source)
        at CCDD.CcddJTableHandler$HTMLCellRenderer.getTableCellRendererComponent(CcddJTableHandler.java:1927)
        at javax.swing.JTable.prepareRenderer(Unknown Source)
        at CCDD.CcddJTableHandler.updateRowHeights(CcddJTableHandler.java:3976)
        at CCDD.CcddJTableHandler.tableChanged(CcddJTableHandler.java:3948)
        at CCDD.CcddJTableHandler$11.run(CcddJTableHandler.java:4086)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at javax.swing.text.Utilities.isComposedTextElement(Unknown Source)
        at javax.swing.text.AbstractDocument.handleRemove(Unknown Source)
        at javax.swing.text.AbstractDocument.remove(Unknown Source)
        at javax.swing.JEditorPane.setText(Unknown Source)
        at CCDD.CcddJTableHandler$HTMLCellRenderer.getTableCellRendererComponent(CcddJTableHandler.java:1927)
        at javax.swing.JTable.prepareRenderer(Unknown Source)
        at CCDD.CcddJTableHandler.updateRowHeights(CcddJTableHandler.java:3976)
        at CCDD.CcddJTableHandler.tableChanged(CcddJTableHandler.java:3948)
        at CCDD.CcddJTableHandler$11.run(CcddJTableHandler.java:4086)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at javax.swing.text.Utilities.isComposedTextElement(Unknown Source)
        at javax.swing.text.AbstractDocument.handleRemove(Unknown Source)
        at javax.swing.text.AbstractDocument.remove(Unknown Source)
        at javax.swing.JEditorPane.setText(Unknown Source)
        at CCDD.CcddJTableHandler$HTMLCellRenderer.getTableCellRendererComponent(CcddJTableHandler.java:1927)
        at javax.swing.JTable.prepareRenderer(Unknown Source)
        at CCDD.CcddJTableHandler.updateRowHeights(CcddJTableHandler.java:3976)
        at CCDD.CcddJTableHandler.tableChanged(CcddJTableHandler.java:3948)
        at CCDD.CcddJTableHandler$11.run(CcddJTableHandler.java:4086)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at javax.swing.text.Utilities.isComposedTextElement(Unknown Source)
        at javax.swing.text.AbstractDocument.handleRemove(Unknown Source)
        at javax.swing.text.AbstractDocument.remove(Unknown Source)
        at javax.swing.JEditorPane.setText(Unknown Source)
        at CCDD.CcddJTableHandler$HTMLCellRenderer.getTableCellRendererComponent(CcddJTableHandler.java:1927)
        at javax.swing.JTable.prepareRenderer(Unknown Source)
        at CCDD.CcddJTableHandler.updateRowHeights(CcddJTableHandler.java:3976)
        at CCDD.CcddJTableHandler.tableChanged(CcddJTableHandler.java:3948)
        at CCDD.CcddJTableHandler$11.run(CcddJTableHandler.java:4086)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at javax.swing.text.Utilities.isComposedTextElement(Unknown Source)
        at javax.swing.text.AbstractDocument.handleRemove(Unknown Source)
        at javax.swing.text.AbstractDocument.remove(Unknown Source)
        at javax.swing.JEditorPane.setText(Unknown Source)
        at CCDD.CcddJTableHandler$HTMLCellRenderer.getTableCellRendererComponent(CcddJTableHandler.java:1927)
        at javax.swing.JTable.prepareRenderer(Unknown Source)
        at CCDD.CcddJTableHandler.updateRowHeights(CcddJTableHandler.java:3976)
        at CCDD.CcddJTableHandler.tableChanged(CcddJTableHandler.java:3948)
        at CCDD.CcddJTableHandler$11.run(CcddJTableHandler.java:4086)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by KevinMcCluney** [comment]
The stack trace in this case isn't providing enough information as to the actual cause.  In order to troubleshoot this I need to see the contents of the associations table (preferably the internal database one, __associations).

**Comment by ascended121** [comment]
Apologies... I can't seem to reproduce the issue this morning. After I reported this yesterday I kept working and must've done something which inadvertently worked around the issue. I'll keep an eye out for it and will dump the __associations table if I see it again.

**Comment by ascended121** [comment]
Actually just started encountering this again with 1.3.8. Attempted to dump the database to take a look at the __associations table, however where I attempt to I get the following error:

```
pg_dump -U dev -w -o -f "C:\myProject.dbu" myProject
--
Project 'myProject' backup failed;  cause 'Cannot run program "pg_dump": CreateProcess error=2, The system cannot find the file specified'
```

I'm not sure I understand the error since I believe pg_dump is supposed to create that file. Similar errors online point to this possibly being an issue with pg_dump not being on the path (which would be a problem I'd need to sort out), but I'm not 100% sure on that. Could you confirm?

Also, when this error occurs I'm unable to close the execute window because the following exception is thrown every time I click the X in the top corner. It seems likely this exception is probably caused by the window having not been created correctly (which is not normal usage), however it would still be nice to be able to close the window without quitting CCDD.

```
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: No such child: -1
        at java.awt.Container.getComponent(Unknown Source)
        at CCDD.CcddButtonPanelHandler.getExitButton(CcddButtonPanelHandler.java:92)
        at CCDD.CcddFrameHandler.windowCloseButtonAction(CcddFrameHandler.java:93)
        at CCDD.CcddFrameHandler$3.windowClosing(CcddFrameHandler.java:269)
        at java.awt.Window.processWindowEvent(Unknown Source)
        at javax.swing.JFrame.processWindowEvent(Unknown Source)
        at java.awt.Window.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by KevinMcCluney** [comment]
I can reproduce the pg_dump error by removing its location from the PATH environment variable.

I believe I've found and corrected the error causing the Script Execute table issue.  It ill be uploaded by COB today.
