### ISSUE TITLE
Exception when attempting to import file - filename?

### ISSUE THREAD

**Issue by ascended121** [nasa/CCDD#42]
Observed following exception when attempting to import a file named `interfaces (1).json`:

```
Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: javax.swing.filechooser.FileNameExtensionFilter cannot be cast to CCDD.CcddDialogHandler$ExtensionFilter
    at CCDD.CcddDialogHandler.choosePathFile(CcddDialogHandler.java:1231)
    at CCDD.CcddTableManagerDialog$1.complete(CcddTableManagerDialog.java:616)
    at CCDD.CcddBackgroundCommand$1.done(CcddBackgroundCommand.java:192)
    at javax.swing.SwingWorker$5.run(SwingWorker.java:737)
    at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:832)
    at sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
    at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:842)
    at javax.swing.Timer.fireActionPerformed(Timer.java:313)
    at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Observed in 1.4.34 on OSX.

**Comment by KevinMcCluney** [comment]
Version 1.4.16 corrects this issue. 
The problem occurs if the file name, without extension, is entered in the file chooser dialog, and multiple file types are selected for display (via the 'Files of Type:' drop down menu).  CCDD attempts to assign the type, but when multiple ones are listed a null result occurs.  The change has it skip adding an extension when multiple are possible.  The result is that the file type can't be discerned and an "unrecognized file type" error dialog is displayed.

**Comment by SpaceSteve121** [comment]
Thanks, no longer observing this on 1.4.48.
