### ISSUE TITLE
Missing Primitive Data Types

### ISSUE THREAD

**Issue by tstern-masten** [nasa/CCDD#93]
Still working through the provided tutorial. 

I got to step 3.5.1, where you have to select a primitive data type for your new variable; however I do not have any data types available in my tool.

Going to manage data types also shows no available data types, primitive or otherwise. 

Do we have to create the primitive data types by hand or should they be automatically populated?

If populated, is that something I might have missed during the install or maybe a misplaced environment variable that could be causing this?

Any and all help is greatly appreciated. Thank you.

**Comment by tstern-masten** [comment]
Looking through logs doesn't indicate any runtime error that I can see so I don't believe that there was an import failure or anything of the sorts.

**Comment by tstern-masten** [comment]
A bit more information on this issue I have found while digging. 

When trying to add padding I got an exception due to not being able to load 'char'

```
CCDD : Database Error : Cannot load table 'char'
CCDD.CcddClassesDataTable$CCDDException: Type "char" is not defined in this database.
        at CCDD.CcddDbTableCommandHandler.UpdateSubTableDataFields(CcddDbTableCommandHandler.java:2661)
        at CCDD.CcddDbTableCommandHandler.BuildReferencedVariablesDataFieldsCmd(CcddDbTableCommandHandler.java:2816)
        at CCDD.CcddDbTableCommandHandler.buildAndExecuteAdditionCommand(CcddDbTableCommandHandler.java:2931)
        at CCDD.CcddDbTableCommandHandler.modifyTableData(CcddDbTableCommandHandler.java:2560)
        at CCDD.CcddPaddingVariableHandler$StructurePaddingHandler.updateTable(CcddPaddingVariableHandler.java:511)
        at CCDD.CcddPaddingVariableHandler$1.execute(CcddPaddingVariableHandler.java:676)
        at CCDD.CcddBackgroundCommand$1.doInBackground(CcddBackgroundCommand.java:148)
        at CCDD.CcddBackgroundCommand$1.doInBackground(CcddBackgroundCommand.java:1)
        at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

Digging into the source code I believe I see where the java source constructs the psql string for inserting the primitive types but this is either not happening or is failing silently.

For reference I am currently using PSQL 10.18 which I think might be responsible for these issues. I am attempting to roll back to 9.4 to see if that resolves these issues.

**Comment by bawillisJSC** [comment]
Just updated version 2.0.27 of CCDD V2

**Comment by tstern-masten** [comment]
Thank you so much for the quick turn around!

I can confirm my problem is resolved with the updated version.
